from typing import _SpecialForm
import requests
from bs4 import BeautifulSoup
import re
import os
import csv

#晴屋用
def setcode2name(self):
    code2name = dict()
    code2name['VOW']='Innistrad: Crimson Vow'
    code2name['MID']='Innistrad: Midnight Hunt'
    code2name['AFR']='Adventures in the Forgotten Realms'
    code2name['AFC']='Adventures in the Forgotten Realms Commander'
    code2name['STX']='Strixhaven: School of Mages'
    code2name['STA']='Strixhaven: Mystical Archive'
    code2name['KHM']='Kaldheim'
    code2name['KHC']='Kaldheim Commander'
    code2name['ZNR']='Zendikar Rising'
    code2name['M21']='Core Set 2021'
    code2name['IKO']='Ikoria: Lair of Behemoths'
    code2name['THB']='Theros: Beyond Death'
    code2name['ELD']='Throne of Eldraine'
    code2name['M20']='Core Set 2020'
    code2name['WAR']='War of the Spark'
    code2name['RNA']='Ravnica Allegiance'
    code2name['GRN']='Guilds of Ravnica'
    code2name['M19']='Core Set 2019'
    code2name['DOM']='Dominaria'
    code2name['RIX']='Rivals of Ixalan'
    code2name['XLN']='Ixalan'
    code2name['HOU']='Hour of Devastation'
    code2name['AKH']='Amonkhet'
    code2name['MS3']='Masterpiece Series: Amonkhet Invocations'
    code2name['AER']='Aether Revolt'
    code2name['KLD']='Kaladesh'
    code2name['MS2']='Masterpiece Series: Kaladesh Inventions'
    code2name['ORI']='Magic Origins'
    code2name['M15']='Magic 2015 Core Set'
    code2name['M14']='Magic 2014 Core Set'
    code2name['EMN']='Eldritch Moon'
    code2name['SOI']='Shadows over Innistrad'
    code2name['OGW']='Oath of the Gatewatch'
    code2name['BFZ']='Battle for Zendikar'
    code2name['EXP']='Zendikar Expeditions'
    code2name['DTK']='Dragons of Tarkir'
    code2name['FRF']='Fate Reforged'
    code2name['KTK']='Khans of Tarkir'
    code2name['JOU']='Journey into Nyx'
    code2name['BNG']='Born of the Gods'
    code2name['THS']='Theros'
    code2name['DGM']='Dragons Maze'
    code2name['GTC']='Gatecrash'
    code2name['RTR']='Return to Ravnica'
    code2name['TSR']='Time Spiral Remastered'
    code2name['MH2']='Modern Horizons 2'
    code2name['MH1']='Modern Horizons'
    code2name['MM3']='Modern Masters 2017 Edition'
    code2name['MM2']='Modern Masters 2015 Edition'
    code2name['MD1']='Modern Event Deck 2014'
    code2name['MMA']='Modern Masters'
    code2name['M13']='Magic 2013'
    code2name['M12']='Magic 2012'
    code2name['M11']='Magic 2011'
    code2name['M10']='Magic 2010'
    code2name['10E']='Tenth Edition'
    code2name['9ED']='Ninth Edition'
    code2name['8ED']='Eighth Edition'
    code2name['AVR']='Avacyn Restored'
    code2name['DKA']='Dark Ascension'
    code2name['ISD']='Innistrad'
    code2name['NPH']='New Phyrexia'
    code2name['MBS']='Mirrodin Besieged'
    code2name['SOM']='Scars of Mirrodin'
    code2name['ROE']='Rise of the Eldrazi'
    code2name['WWK']='Worldwake'
    code2name['ZEN']='Zendikar'
    code2name['ARB']='Alara Reborn'
    code2name['CON']='Conflux'
    code2name['ALA']='Shards of Alara'
    code2name['EVE']='Eventide'
    code2name['SHM']='Shadowmoor'
    code2name['MOR']='Morningtide'
    code2name['LRW']='Lorwyn'
    code2name['FUT']='Future Sight'
    code2name['PLC']='Planar Chaos'
    code2name['TSP']='Time Spiral'
    code2name['TSB']='Time Spiral "Timeshifted"'
    code2name['CSP']='Coldsnap'
    code2name['DIS']='Dissension'
    code2name['GPT']='Guildpact'
    code2name['RAV']='Ravnica: City of Guilds'
    code2name['SOK']='Saviors of Kamigawa'
    code2name['BOK']='Betrayers of Kamigawa'
    code2name['CHK']='Champions of Kamigawa'
    code2name['5DN']='Fifth Dawn'
    code2name['DST']='Darksteel'
    code2name['MRD']='Mirrodin'
    code2name['7ED']='Seventh Edition'
    code2name['6ED']='Classic Sixth Edition'
    code2name['5ED']='Fifth Edition'
    code2name['4ED']='Fourth Edition'
    code2name['3ED']='Revised Edition'
    code2name['2ED']='Unlimited Edition'
    code2name['LEB']='Limited Edition Beta'
    code2name['LEA']='Limited Edition Alpha'
    code2name['SCG']='Scourge'
    code2name['LGN']='Legions'
    code2name['ONS']='Onslaught'
    code2name['JUD']='Judgment'
    code2name['TOR']='Torment'
    code2name['ODY']='Odyssey'
    code2name['APC']='Apocalypse'
    code2name['PLS']='Planeshift'
    code2name['INV']='Invasion'
    code2name['PCY']='Prophecy'
    code2name['NEM']='Nemesis'
    code2name['MMQ']='Mercadian Masques'
    code2name['UDS']='Urzas Destiny'
    code2name['ULG']='Urzas Legacy'
    code2name['USG']='Urzas Saga'
    code2name['EXO']='Exodus'
    code2name['STH']='Stronghold'
    code2name['TMP']='Tempest'
    code2name['WTH']='Weatherlight'
    code2name['VIS']='Visions'
    code2name['MIR']='Mirage'
    code2name['CSP']='Coldsnap'
    code2name['ALL']='Alliances'
    code2name['HML']='Homelands'
    code2name['ICE']='Ice Age'
    code2name['FEM']='Fallen Empires'
    code2name['DRK']='The Dark'
    code2name['LEG']='Legends'
    code2name['ATQ']='Antiquities'
    code2name['ARN']='Arabian Nights'
    code2name['J21']='Jumpstart: Historic Horizons'
    code2name['SLD']='Secret Lair'
    code2name['PSLD']='Secret Lair Promos'
    code2name['MB1']='Mystery Booster'
    code2name['2XM']='Double Masters'
    code2name['UMA']='Ultimate Masters'
    code2name['UBT']='Ultimate Box Topper'
    code2name['A25']='Masters 25'
    code2name['IMA']='Iconic Masters'
    code2name['EMA']='Eternal Masters'
    code2name['VMA']='Vintage Masters'
    code2name['JMP']='Jumpstart'
    code2name['BBD']='Battlebond'
    code2name['E02']='Explorers of Ixalan'
    code2name['CN2']='Conspiracy: Take the Crown'
    code2name['CNS']='Conspiracy'
    code2name['C21']='Commander 2021'
    code2name['C20']='Commander 2020'
    code2name['C19']='Commander 2019'
    code2name['C18']='Commander 2018'
    code2name['C17']='Commander 2017'
    code2name['C16']='Commander 2016'
    code2name['C15']='Commander 2015'
    code2name['C14']='Commander 2014'
    code2name['C13']='Commander 2013 Edition'
    code2name['CMD']='Magic: The Gathering-Commander'
    code2name['CMR']='Commander Legends'
    code2name['CM2']='Commander Anthology 2018'
    code2name['CMA']='Commanders Arsenal'
    code2name['POR']='Portal'
    code2name['PO2']='Portal Second Age'
    code2name['PTK']='Portal Three Kingdoms'
    code2name['S00']='Starter 2000'
    code2name['S99']='Starter 1999'
    code2name['DDU']='Duel Decks: Elves vs Inventors'
    code2name['DDT']='Duel Decks: Merfolk vs Goblins'
    code2name['DDS']='Duel Decks: Mind vs Might'
    code2name['DD3_DVD']='Duel Decks Anthology, Divine vs Demonic'
    code2name['DD3_EVG']='Duel Decks Anthology, Elves vs Goblins'
    code2name['DD3_GVL']='Duel Decks Anthology, Garruk vs Liliana'
    code2name['DD3_JVC']='Duel Decks Anthology, Jace vs Chandra'
    code2name['NvN']='Duel Decks: Nissa vs Ob Nixilis'
    code2name['BvC']='Duel Decks: Blessed vs Cursed'
    code2name['ZvE']='Duel Decks: Zendikar vs Eldrazi'
    code2name['EvK']='Duel Decks: Elspeth vs Kiora'
    code2name['SvC']='Duel Decks: Speed vs Cunning'
    code2name['JvV']='Duel Decks: Jace vs Vraska'
    code2name['HvM']='Duel Decks: Heroes vs Monsters'
    code2name['SvT']='Duel Decks: Sorin vs Tibalt'
    code2name['IvG']='Duel Decks: Izzet vs Golgari'
    code2name['VvK']='Duel Decks: Venser vs Koth'
    code2name['AvN']='Duel Decks: Ajani vs Nicol Bolas'
    code2name['KvD']='Duel Decks: Knights vs Dragons'
    code2name['EvT']='Duel Decks: Elspeth vs Tezzeret'
    code2name['PvC']='Duel Decks: Phyrexia vs the Coalition'
    code2name['GvL']='Duel Decks: Garruk vs Liliana'
    code2name['DvD']='Duel Decks: Divine vs Demonic'
    code2name['JvC']='Duel Decks: Jace vs Chandra'
    code2name['EVG']='Duel Decks: Elves vs Goblins'
    code2name['GK1']='Guilds of Ravnica Guild Kits'
    code2name['GK2']='Ravnica Allegiance Guild Kits'
    code2name['SS1']='Signature Spellbook: Jace'
    code2name['SS2']='Signature Spellbook: Gideon'
    code2name['SS3']='Signature Spellbook: Chandra'
    code2name['V17']='From the Vault: Transform'
    code2name['V16']='From the Vault: Lore'
    code2name['V15']='From the Vault: Angels'
    code2name['V14']='From the Vault: Annihilation'
    code2name['V13']='From the Vault: Twenty'
    code2name['V12']='From the Vault: Realms'
    code2name['V11']='From the Vault: Legends'
    code2name['V10']='From the Vault: Relics'
    code2name['V09']='From the Vault: Exiled'
    code2name['DRB']='From the Vault: Dragons'
    code2name['PC1']='Planechase'
    code2name['PC2']='Planechase 2012 Edition'
    code2name['PCA']='Planechase Anthology'
    code2name['GRB']='Premium Deck Series: Graveborn'
    code2name['PD2']='Premium Deck Series: Fire and Lightning'
    code2name['H09']='Premium Deck Series: Slivers'
    code2name['E01']='Archenemy: Nicol Bolas'
    code2name['ARC']='Archenemy'
    code2name['BTD']='Beatdown Box Set'
    code2name['BRB']='Battle Royale Box Set'
    code2name['ATH']='Anthologies'
    code2name['CHR']='Chronicles'
    code2name['UND']='Unsanctioned'
    code2name['UST']='Unstable'
    code2name['UNH']='Unhinged'
    code2name['UGL']='Unglued'
    code2name['PZ2']='Treasure Chest'
    code2name['PZ1']='Legendary Cube (Prize Packs)'
    code2name['TPR']='Tempest Remastered'
    code2name['ME4']='Masters Edition IV'
    code2name['ME3']='Masters Edition III'
    code2name['ME2']='Masters Edition II'
    code2name['MED']='Masters Edition'
    code2name['MED-WAR']='War of the Spark Masterpieces'
    code2name['MED-RNA']='Ravnica Allegiance Masterpieces'
    code2name['MED-GRN']='Guilds of Ravnica Masterpieces'
    code2name['MS3']='Masterpiece Series: Amonkhet Invocations'
    code2name['MS2']='Masterpiece Series: Kaladesh Inventions'
    code2name['ZNE']='Zendikar Rising Expeditions'
    code2name['PRM']='Magic Online Promo'
    code2name['PRM-BAB']='Buy-A-Box Promos'
    code2name['PRM-SSP']='Standard Showdown Promos'
    code2name['PRM-UGF']='Ugins Fate Promos'
    code2name['PTG']='Ponies: The Galloping'
    code2name['PRM-SDCC18']='SDCC 2018 Promos'
    code2name['PRM-SDCC17']='SDCC 2017 Promos'
    code2name['PRM-SDCC16']='SDCC 2016 Promos'
    code2name['PRM-SDCC15']='SDCC 2015 Promos'
    code2name['PRM-SDCC14']='SDCC 2014 Promos'
    code2name['PRM-SDCC13']='SDCC 2013 Promos'
    code2name['PRM-CHP']='Champs Promos'
    code2name['FNM']='FNM Promos'
    code2name['PRM-GDP']='Game Day Promos'
    code2name['PRM-GWP']='Gateway Promos'
    code2name['GPプ']='Grand Prix Promos'
    code2name['PRM-GUR']='Guru Lands'
    code2name['PRM-JSS']='JSS/MSS Promos'
    code2name['PRM-JUD']='Judge Promos'
    code2name['PRM-LPC']='Launch Party Cards'
    code2name['PRM-MPR']='Magic Player Rewards'
    code2name['PRM-MED']='Media Promos'
    code2name['PRM-PRE']='Prerelease Cards'
    code2name['PRM-PTP']='Pro Tour Promos'
    code2name['PRM-REL']='Release Event Cards'
    code2name['PRM-SPO']='Special Occasion'
    code2name['PRM-MSC']='Unique and Miscellaneous Promos'
    code2name['PRM-WPN']='WPN & Gateway Promos'
    code2name['DKM']='Deckmasters'
    code2name['The']='The List'
    code2name['Sec']='Secret Lair'
    code2name['404']='404'
    
    
    if self == 'SDC' :
        self = '404'
        return code2name['404']
    elif self == 'BOX':
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == 'Mag':
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == 'ジャッ':
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == 'MPS':#待處理
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == 'FtV':#待處理
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == '':
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == 'その他':
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == '発売記':#售限
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == 'PWC':
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == '褒賞プ':#player reward 待處理
        self = '404'
        #code2name['404']='404'
        return code2name['404']
    elif self == 'ゲーム':
        return code2name['404']
    else:
        return code2name[self]




